# mysql数据库配置
[mysql]
# 连接地址
host = "127.0.0.1"
# 连接端口
port= "3306"
# 用户名
user = "root"
# 密码
password = "123456"
# 数据库
db_name = "ginadmin"
# 连接参数
parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"